"""transform_student_model_to_phone_based_auth

Revision ID: 0e56ca3be26a
Revises: f7d5e869135a
Create Date: 2025-06-30 10:40:07.127476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e56ca3be26a'
down_revision: Union[str, Sequence[str], None] = 'f7d5e869135a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('students', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_students_phone_number'), 'students', ['phone_number'], unique=True)
    op.drop_column('students', 'email_verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_phone_number'), table_name='students')
    op.alter_column('students', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('students', 'phone_verified_at')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'phone_number')
    # ### end Alembic commands ###
