"""Add contact number and contact staff ID to college model

Revision ID: 215b80b89ae8
Revises: change_to_full_name_1750395737
Create Date: 2025-06-21 13:37:49.685310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215b80b89ae8'
down_revision: Union[str, Sequence[str], None] = 'change_to_full_name_1750395737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('contact_number', sa.String(length=20), nullable=True))
    op.add_column('colleges', sa.Column('contact_staff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_colleges_contact_staff_id_staff'), 'colleges', 'staff', ['contact_staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_colleges_contact_staff_id_staff'), 'colleges', type_='foreignkey')
    op.drop_column('colleges', 'contact_staff_id')
    op.drop_column('colleges', 'contact_number')
    # ### end Alembic commands ###
