"""Add profile_completed column 
  to cms_users

Revision ID: 36e923f780ed
Revises: 
Create Date: 2025-06-13 03:27:41.805103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36e923f780ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_users', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.alter_column('cms_users', 'college_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cms_users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cms_users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cms_users', 'role',
               existing_type=postgresql.ENUM('principal', 'admin', 'head', 'staff', name='cms_user_role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_users', 'role',
               existing_type=postgresql.ENUM('principal', 'admin', 'head', 'staff', name='cms_user_role'),
               nullable=False)
    op.alter_column('cms_users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cms_users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cms_users', 'college_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('cms_users', 'profile_completed')
    # ### end Alembic commands ###