"""Add user_sessions table for multi-device authentication

Revision ID: 4fc8bd71e176
Revises: 215b80b89ae8
Create Date: 2025-06-21 16:23:17.627154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc8bd71e176'
down_revision: Union[str, Sequence[str], None] = '215b80b89ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_colleges_principal_cms_staff_id_staff'), 'colleges', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_colleges_principal_cms_staff_id_staff'), 'colleges', 'staff', ['principal_cms_staff_id'], ['id'])
    # ### end Alembic commands ###
