"""Initial migration with all models

Revision ID: d409c5e22560
Revises: 
Create Date: 2025-07-01 08:47:16.207832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd409c5e22560'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('division_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_departments_division_id_divisions'), 'departments', 'divisions', ['division_id'], ['division_id'])
    op.drop_column('divisions', 'is_active')
    op.add_column('staff', sa.Column('contact_number', sa.String(length=20), nullable=False))
    op.add_column('staff', sa.Column('division_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_staff_division_id_divisions'), 'staff', 'divisions', ['division_id'], ['division_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_staff_division_id_divisions'), 'staff', type_='foreignkey')
    op.drop_column('staff', 'division_id')
    op.drop_column('staff', 'contact_number')
    op.add_column('divisions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_departments_division_id_divisions'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'division_id')
    # ### end Alembic commands ###
