name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  AWS_REGION: ap-south-1

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          # Add linting commands here when available
          echo "Linting step - configure ruff/mypy commands"

      - name: Run type checking
        run: |
          # Add type checking commands here when available
          echo "Type checking step - configure mypy commands"

      - name: Run unit tests
        run: |
          # Add test commands here when test suite is available
          echo "Unit tests step - configure pytest commands"

  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/arm64
          tags: turtil-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max