name: Terraform Plan

on:
  pull_request:
    branches: [main, dev]
    paths:
      - 'terraform-files/**'
      - '.github/workflows/terraform-plan.yml'

env:
  AWS_REGION: ap-south-1
  TF_VERSION: 1.5.0

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Load Environment Variables
        run: |
          echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ./terraform-files
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform-files
        run: terraform plan -out=tfplan-${{ env.ENVIRONMENT }}
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_upstash_redis_url: ${{ secrets.UPSTASH_REDIS_URL }}
          TF_VAR_upstash_redis_token: ${{ secrets.UPSTASH_REDIS_TOKEN }}
          TF_VAR_aws_ses_from_email: ${{ secrets.AWS_SES_FROM_EMAIL }}

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ env.ENVIRONMENT }}
          path: terraform-files/tfplan-${{ env.ENVIRONMENT }}
          retention-days: 5